const workouts=[
{id:"w1",name:"Strength Foundation",cat:"Strength",level:"Beginner",weeks:6,min:45,sessions:18,img:"https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80",desc:"Build total-body strength with progressive compound movements and a simple three-day split."},
{id:"w2",name:"Hypertrophy Builder",cat:"Muscle",level:"Intermediate",weeks:8,min:60,sessions:32,img:"https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=900&q=80",desc:"A structured muscle-building program focused on volume, progressive overload and recovery."},
{id:"w3",name:"HIIT Engine",cat:"Cardio",level:"Intermediate",weeks:4,min:30,sessions:16,img:"https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=900&q=80",desc:"Fast, athletic interval sessions designed to improve conditioning and work capacity."},
{id:"w4",name:"Lower Body Power",cat:"Strength",level:"Advanced",weeks:6,min:50,sessions:18,img:"https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=900&q=80",desc:"Develop stronger legs and explosive power with squat, hinge and unilateral training."},
{id:"w5",name:"Core & Mobility",cat:"Mobility",level:"All levels",weeks:4,min:25,sessions:20,img:"https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80",desc:"Improve trunk strength, movement quality and mobility with short repeatable sessions."},
{id:"w6",name:"Lean & Fit",cat:"Fat Loss",level:"Beginner",weeks:8,min:40,sessions:32,img:"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=900&q=80",desc:"A balanced mix of resistance training and conditioning for sustainable fitness progress."}
];
const classes=[
{id:"c1",name:"Power HIIT",coach:"Maya Chen",time:"07:00",duration:45,capacity:18},
{id:"c2",name:"Strength Lab",coach:"Adam Lee",time:"10:00",duration:60,capacity:14},
{id:"c3",name:"Yoga Flow",coach:"Sofia Rahman",time:"13:30",duration:50,capacity:20},
{id:"c4",name:"Box & Burn",coach:"Daniel Wong",time:"18:00",duration:45,capacity:16},
{id:"c5",name:"Pilates Core",coach:"Nadia Lim",time:"19:00",duration:50,capacity:18},
{id:"c6",name:"Cycle Rush",coach:"Chris Tan",time:"20:00",duration:40,capacity:22}
];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const activity=()=>JSON.parse(localStorage.getItem("pulse_activity")||"[]");
const save=a=>localStorage.setItem("pulse_activity",JSON.stringify(a));
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2000)}
function showView(id){$$(".view").forEach(v=>v.classList.toggle("active",v.id===id));$$(".navlink").forEach(b=>b.classList.toggle("active",b.dataset.view===id));if(id==="classes")renderClasses();if(id==="progress")renderProgress();if(id==="admin")renderAdmin();scrollTo({top:0,behavior:"smooth"})}
function renderFilters(){let cats=["All",...new Set(workouts.map(w=>w.cat))];$("#workoutFilters").innerHTML=cats.map((c,i)=>`<button class="chip ${i?"":"active"}" data-cat="${c}">${c}</button>`).join("");$$(".chip").forEach(b=>b.onclick=()=>{$$(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderWorkouts(b.dataset.cat)})}
function renderWorkouts(cat="All"){let data=workouts.filter(w=>cat==="All"||w.cat===cat);$("#workoutGrid").innerHTML=data.map(w=>`<article class="card"><img class="cardimg" src="${w.img}" alt="${w.name}"><div class="cardbody"><span class="tag">${w.cat.toUpperCase()} · ${w.weeks} WEEKS</span><h3>${w.name}</h3><p class="meta">${w.min} min/session · ${w.sessions} sessions</p><div class="cardfoot"><span class="level">${w.level}</span><button class="btn darkbtn" onclick="openWorkout('${w.id}')">VIEW PLAN</button></div></div></article>`).join("")}
window.openWorkout=id=>{let w=workouts.find(x=>x.id===id);$("#modalContent").innerHTML=`<img class="modalimg" src="${w.img}"><div class="modalinner"><span class="kicker dark">${w.cat.toUpperCase()} PROGRAM</span><h2>${w.name}</h2><p>${w.desc}</p><div class="detailrow"><div><b>${w.weeks}</b><br><small>Weeks</small></div><div><b>${w.min}</b><br><small>Min/session</small></div><div><b>${w.sessions}</b><br><small>Sessions</small></div></div><button class="btn lime" onclick="completeWorkout('${w.id}')">COMPLETE A SESSION</button></div>`;$("#workoutModal").hidden=false}
window.completeWorkout=id=>{let w=workouts.find(x=>x.id===id),a=activity();a.unshift({type:"workout",name:w.name,minutes:w.min,date:new Date().toISOString()});save(a);$("#workoutModal").hidden=true;toast("Workout logged — nice work!")}
function renderClasses(){let booked=activity().filter(a=>a.type==="class").map(a=>a.id);$("#classGrid").innerHTML=classes.map(c=>`<article class="classcard"><div><span class="kicker dark">${c.duration} MIN · COACH ${c.coach.toUpperCase()}</span><h3>${c.name}</h3><span class="spots">${c.capacity} studio spots</span></div><div><div class="time">${c.time}</div><button class="btn ${booked.includes(c.id)?"outline":"lime"}" onclick="bookClass('${c.id}')" ${booked.includes(c.id)?"disabled":""}>${booked.includes(c.id)?"BOOKED":"BOOK"}</button></div></article>`).join("")}
window.bookClass=id=>{let c=classes.find(x=>x.id===id),a=activity();if(a.some(x=>x.type==="class"&&x.id===id))return;a.unshift({type:"class",id,name:c.name,minutes:c.duration,date:new Date().toISOString()});save(a);renderClasses();toast(`${c.name} booked`)}
function renderProgress(){let a=activity(),ws=a.filter(x=>x.type==="workout"),cs=a.filter(x=>x.type==="class");$("#doneCount").textContent=ws.length;$("#minutesCount").textContent=ws.reduce((s,x)=>s+x.minutes,0);$("#bookedCount").textContent=cs.length;$("#streakCount").textContent=(ws.length?Math.min(ws.length,7):0)+" days";$("#activityList").innerHTML=a.length?a.slice(0,8).map(x=>`<div class="activity"><div><b>${x.name}</b><br><small>${x.type==="workout"?"Workout completed":"Class reserved"}</small></div><div>${x.minutes} min<br><small>${new Date(x.date).toLocaleDateString()}</small></div></div>`).join(""):`<p class="lead">No activity yet. Complete a workout or book a class to start tracking progress.</p>`}
function renderAdmin(){let auth=sessionStorage.getItem("pulse_admin")==="1";$("#loginBox").hidden=auth;$("#dashboard").hidden=!auth;if(auth){let booked=activity().filter(x=>x.type==="class");$("#adminBookings").textContent=booked.length;$("#classRows").innerHTML=classes.map(c=>`<tr><td><b>${c.name}</b></td><td>${c.coach}</td><td>${c.time}</td><td>${Math.max(0,c.capacity-booked.filter(x=>x.id===c.id).length)} / ${c.capacity} available</td><td><span class="status">SCHEDULED</span></td></tr>`).join("")}}
$$("[data-view]").forEach(b=>b.onclick=e=>{e.preventDefault();showView(b.dataset.view)});
$$("[data-go]").forEach(b=>b.onclick=()=>showView(b.dataset.go));
$("#joinBtn").onclick=()=>{$("#workoutSection").scrollIntoView({behavior:"smooth"})};$("#exploreBtn").onclick=()=>$("#workoutSection").scrollIntoView({behavior:"smooth"});
$(".close").onclick=()=>$("#workoutModal").hidden=true;$("#workoutModal").onclick=e=>{if(e.target===$("#workoutModal"))$("#workoutModal").hidden=true};
$("#loginForm").onsubmit=e=>{e.preventDefault();if($("#email").value==="admin@pulsefit.com"&&$("#password").value==="admin123"){sessionStorage.setItem("pulse_admin","1");renderAdmin();toast("Welcome to PULSE staff portal")}else toast("Invalid demo credentials")};
$("#logout").onclick=()=>{sessionStorage.removeItem("pulse_admin");renderAdmin()};
renderFilters();renderWorkouts();